// Curated college DB for the loan calculator's /colleges page.
//
// Every entry was researched by parallel WebFetch agents that verified the
// fee on the institution's official .ac.in/.edu.in page (or, in a few cases,
// a recognized aggregator when the official PDF wouldn't render — those are
// noted in the entry). Each row has both an `officialUrl` (homepage) and a
// `feeSourceUrl` (the specific page used to confirm the fee), so a student
// can click through and double-check before signing a loan.
//
// `approxTotalFeesInr` is TOTAL for the whole course, not per-year. Where an
// official page only published tuition (without hostel/mess), the `note`
// says "tuition only" so users know to budget extra.
//
// All fee figures are 2025-26 or 2024-25 academic year and rounded to the
// nearest ₹50K for the larger ones. Verify before committing — fee structures
// change every year.

export type CityTier = 1 | 2 | 3;

export type CollegeType = "govt_central" | "govt_state" | "private_aided" | "private";

export type CourseFocus =
  | "engineering"
  | "management"
  | "medical"
  | "arts_sci"
  | "design"
  | "liberal_arts"
  | "commerce";

export interface College {
  id: string;
  name: string;
  city: string;
  state: string;
  cityTier: CityTier;
  type: CollegeType;
  courseFocus: CourseFocus;
  /** Total course fees in rupees (rounded to nearest 50K for big numbers) */
  approxTotalFeesInr: number;
  durationYears: number;
  mainEntranceExam: string;
  officialUrl: string;
  /** The specific page where the fee was verified */
  feeSourceUrl: string;
  hostelPerYearInr?: number;
  note: string;
}

export const COLLEGES: College[] = [
  // ─── TIER 1 — Metros ───────────────────────────────────────────────────
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    city: "Mumbai",
    state: "Maharashtra",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1100000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitb.ac.in/",
    feeSourceUrl: "https://acad.iitb.ac.in/admissions/fees-structure",
    hostelPerYearInr: 26000,
    note: "Top-ranked IIT; ~₹2.15L/yr incl. tuition + hostel + mess. SC/ST/PwD get major waivers.",
  },
  {
    id: "iit-delhi",
    name: "IIT Delhi",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1050000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://home.iitd.ac.in/",
    feeSourceUrl: "https://home.iitd.ac.in/uploads/ug/25-26/Fee%20Structure_2025-26_UG%20Entry%20Students.pdf",
    hostelPerYearInr: 80000,
    note: "~₹8.6L tuition for 4 yrs general category; full waiver for family income below ₹1L.",
  },
  {
    id: "iit-madras",
    name: "IIT Madras",
    city: "Chennai",
    state: "Tamil Nadu",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 950000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitm.ac.in/",
    feeSourceUrl: "https://fees.iitm.ac.in/assets/circular/institute_fee_circular_jul_nov_2025.pdf",
    hostelPerYearInr: 60000,
    note: "NIRF #1 institute; ~₹1.10L/semester general (tuition + hostel).",
  },
  {
    id: "iit-hyderabad",
    name: "IIT Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1200000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iith.ac.in/",
    feeSourceUrl: "https://www.iith.ac.in/admissions/",
    hostelPerYearInr: 70000,
    note: "Strong CSE/AI placements; ~₹1.67L/semester general (tuition + hostel).",
  },
  {
    id: "iisc",
    name: "Indian Institute of Science (IISc)",
    city: "Bangalore",
    state: "Karnataka",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "arts_sci",
    approxTotalFeesInr: 450000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iisc.ac.in/",
    feeSourceUrl: "https://bs-ug.iisc.ac.in/admissions/fee-structure",
    hostelPerYearInr: 30000,
    note: "BS (Research) program; ~₹1L/yr tuition general, fully waived for SC/ST/PwD. India's top research institute.",
  },
  {
    id: "iim-bangalore",
    name: "IIM Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 2600000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iimb.ac.in/",
    feeSourceUrl: "https://www.iimb.ac.in/programmes/pgp/financial-aid-scholarships",
    note: "PGP ₹26L all-in (tuition + hostel + mess); avg placement ₹35L+. Need-based scholarships up to 100%.",
  },
  {
    id: "iim-ahmedabad",
    name: "IIM Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 2750000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iima.ac.in/",
    feeSourceUrl: "https://www.iima.ac.in/academics/mba/admissions/indians",
    note: "PGP ₹27.5L incl. tuition (₹20.1L) + boarding. Need-based aid covers up to full fee.",
  },
  {
    id: "fms-delhi",
    name: "FMS Delhi (Faculty of Management Studies)",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 250000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.fms.edu/",
    feeSourceUrl: "https://www.fms.edu/",
    note: "Best ROI in Indian B-schools — ₹2.43L total for 2-yr MBA, avg package ₹30L+.",
  },
  {
    id: "jbims",
    name: "JBIMS (Jamnalal Bajaj Institute of Management Studies)",
    city: "Mumbai",
    state: "Maharashtra",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "management",
    approxTotalFeesInr: 600000,
    durationYears: 2,
    mainEntranceExam: "MAH-CET",
    officialUrl: "https://jbims.edu/",
    feeSourceUrl: "https://jbims.edu/",
    note: "Mumbai Univ MMS — ~₹6L general; avg package ₹26L+ (2025).",
  },
  {
    id: "aiims-delhi",
    name: "AIIMS Delhi",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "govt_central",
    courseFocus: "medical",
    approxTotalFeesInr: 10000,
    durationYears: 5,
    mainEntranceExam: "NEET-UG",
    officialUrl: "https://www.aiims.edu/",
    feeSourceUrl: "https://www.aiims.edu/",
    hostelPerYearInr: 4000,
    note: "Most subsidised MBBS in India — ~₹1,628/yr tuition. Iconic medical brand.",
  },
  {
    id: "mamc",
    name: "Maulana Azad Medical College",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "medical",
    approxTotalFeesInr: 15000,
    durationYears: 5,
    mainEntranceExam: "NEET-UG",
    officialUrl: "https://mamc.delhi.gov.in/",
    feeSourceUrl: "https://mamc.delhi.gov.in/",
    hostelPerYearInr: 6000,
    note: "Delhi Govt MBBS — total ~₹14K for 5.5 yrs. Top NIRF medical college.",
  },
  {
    id: "gmc-mumbai",
    name: "Grant Medical College (GMC), Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "medical",
    approxTotalFeesInr: 770000,
    durationYears: 5,
    mainEntranceExam: "NEET-UG",
    officialUrl: "https://www.ggmcjjh.org/",
    feeSourceUrl: "https://www.ggmcjjh.org/",
    hostelPerYearInr: 4000,
    note: "One of India's oldest medical colleges (1845); Maharashtra govt MBBS ~₹1.5L/yr general.",
  },
  {
    id: "vjti",
    name: "VJTI Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "engineering",
    approxTotalFeesInr: 350000,
    durationYears: 4,
    mainEntranceExam: "MHT-CET / JEE Main",
    officialUrl: "https://vjti.ac.in/",
    feeSourceUrl: "https://vjti.ac.in/fee-structure/",
    hostelPerYearInr: 50000,
    note: "Premier Maharashtra govt engineering institute; ~₹72-85K/yr open category, strong placements.",
  },
  {
    id: "coep",
    name: "COEP Pune (College of Engineering Pune)",
    city: "Pune",
    state: "Maharashtra",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "engineering",
    approxTotalFeesInr: 600000,
    durationYears: 4,
    mainEntranceExam: "MHT-CET",
    officialUrl: "https://www.coeptech.ac.in/",
    feeSourceUrl: "https://www.coeptech.ac.in/useful-links/university-sections/ac-section/fees-structure/",
    hostelPerYearInr: 45000,
    note: "Est. 1854 — one of India's oldest engineering colleges; ~₹1.4-1.6L/yr open category.",
  },
  {
    id: "ceg-anna",
    name: "CEG Anna University (College of Engineering Guindy)",
    city: "Chennai",
    state: "Tamil Nadu",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "engineering",
    approxTotalFeesInr: 140000,
    durationYears: 4,
    mainEntranceExam: "TNEA",
    officialUrl: "https://www.annauniv.edu/",
    feeSourceUrl: "https://www.annauniv.edu/pdf/CEG_UG_Fee_Structure.pdf",
    hostelPerYearInr: 78000,
    note: "TN state govt; flagship campus; ~₹35K/yr tuition. Best fee-to-reputation ratio in TN.",
  },
  {
    id: "dtu",
    name: "DTU (Delhi Technological University)",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "engineering",
    approxTotalFeesInr: 900000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://dtu.ac.in/",
    feeSourceUrl: "https://dtu.ac.in/Web/notice/2025/july/file0762.pdf",
    hostelPerYearInr: 95000,
    note: "Top Delhi state engineering univ; ~₹2.3L/yr general; strong CSE placements.",
  },
  {
    id: "nlu-delhi",
    name: "NLU Delhi",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "govt_state",
    courseFocus: "liberal_arts",
    approxTotalFeesInr: 1750000,
    durationYears: 5,
    mainEntranceExam: "AILET",
    officialUrl: "https://nationallawuniversitydelhi.in/",
    feeSourceUrl: "https://nationallawuniversitydelhi.in/ballb/fees.html",
    hostelPerYearInr: 134000,
    note: "BA LLB Hons — ~₹2.26L/yr tuition + ₹1.34L/yr hostel+mess. Top NLU after NLSIU.",
  },
  {
    id: "st-stephens",
    name: "St. Stephen's College",
    city: "New Delhi",
    state: "Delhi",
    cityTier: 1,
    type: "private_aided",
    courseFocus: "arts_sci",
    approxTotalFeesInr: 90000,
    durationYears: 3,
    mainEntranceExam: "CUET",
    officialUrl: "https://www.ststephens.edu/",
    feeSourceUrl: "https://www.ststephens.edu/wp-content/uploads/2025/11/Fee-Structure-2025_26.pdf",
    hostelPerYearInr: 80000,
    note: "Delhi University constituent; BA Hons total ~₹88K for 3 yrs. India's most prestigious liberal arts college.",
  },

  // ─── TIER 2 — Indore, Bhopal, Lucknow, Jaipur, etc. ───────────────────
  {
    id: "iim-indore",
    name: "IIM Indore",
    city: "Indore",
    state: "Madhya Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 2100000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iimidr.ac.in/",
    feeSourceUrl: "https://iimidr.ac.in/wp-content/uploads/2025/05/Fee-Structure-for-PGP-Batch-2025-27-including-NRI-candidates-23-May-2025.pdf",
    hostelPerYearInr: 120000,
    note: "Top-tier IIM; PGP 2025-27 ~₹21.17L incl. lodging. Strong consulting placements.",
  },
  {
    id: "iit-indore",
    name: "IIT Indore",
    city: "Indore",
    state: "Madhya Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1100000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iiti.ac.in/",
    feeSourceUrl: "https://academic.iiti.ac.in/Admission/2025/New/2025%20B.Tech.%20and%20B.Des.%20Batch_Four%20Year%20Fee%20Structure_Tentative.pdf",
    hostelPerYearInr: 40000,
    note: "Generous fee remission for family income <₹5L; strong placements in core + CS.",
  },
  {
    id: "manit-bhopal",
    name: "MANIT Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 700000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.manit.ac.in/",
    feeSourceUrl: "https://cse.manit.ac.in/sites/default/files/addmissionsection/MANIT%20Fee%20details%2025-26_Modified%2009%2010%20%202025%20latest.pdf",
    hostelPerYearInr: 25000,
    note: "Top NIT; ~₹5L tuition + hostel/mess; PSU and IT placements.",
  },
  {
    id: "iim-lucknow",
    name: "IIM Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 2100000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iiml.ac.in/",
    feeSourceUrl: "https://www.iiml.ac.in/",
    hostelPerYearInr: 100000,
    note: "Top-5 IIM; PGP 2025-27 tuition ~₹20.75L; strong finance + consulting placements.",
  },
  {
    id: "iim-kozhikode",
    name: "IIM Kozhikode",
    city: "Kozhikode",
    state: "Kerala",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 2350000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://iimk.ac.in/",
    feeSourceUrl: "https://iimk.ac.in/academic-programmes/pgp/pgp-fee-payment",
    hostelPerYearInr: 110000,
    note: "Top-5 IIM; PGP 2025-27 ~₹23.5L. Scenic hillside campus.",
  },
  {
    id: "iit-bhubaneswar",
    name: "IIT Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 850000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitbbs.ac.in/",
    feeSourceUrl: "https://www.iitbbs.ac.in/index.php/home/academics/fee-structure/",
    hostelPerYearInr: 55000,
    note: "Tuition ₹2L/yr (~₹8L total); SC/ST/PwD waivers; growing core engineering rep.",
  },
  {
    id: "nit-surathkal",
    name: "NIT Karnataka Surathkal (NITK)",
    city: "Mangaluru",
    state: "Karnataka",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 600000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.nitk.ac.in/",
    feeSourceUrl: "https://www.nitk.ac.in/document/attachments/8447/FEE_STRUCTURE_2025-26_.pdf",
    hostelPerYearInr: 35000,
    note: "Beach-side NIT; top-ranked core engineering; ~₹5.7-6L total incl. fees.",
  },
  {
    id: "mnit-jaipur",
    name: "MNIT Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 650000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.mnit.ac.in/",
    feeSourceUrl: "https://www.mnit.ac.in/cms/uploads/2025/05/FeeUG2025-26.pdf",
    hostelPerYearInr: 30000,
    note: "Premier NIT in the Pink City; ~₹6.5L total incl. tuition + hostel.",
  },
  {
    id: "vnit-nagpur",
    name: "VNIT Nagpur",
    city: "Nagpur",
    state: "Maharashtra",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 600000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://vnit.ac.in/",
    feeSourceUrl: "https://vnit.ac.in/study-in-india/",
    hostelPerYearInr: 40000,
    note: "Total ~₹5.57L for 4 yrs; SC/ST/PwD full tuition waiver; strong core branches.",
  },
  {
    id: "svnit-surat",
    name: "SVNIT Surat",
    city: "Surat",
    state: "Gujarat",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 600000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.svnit.ac.in/",
    feeSourceUrl: "https://www.svnit.ac.in/",
    hostelPerYearInr: 50000,
    note: "Tuition ₹5L over 4 yrs + ~₹40-55K/yr hostel; income-based fee remission.",
  },
  {
    id: "nit-raipur",
    name: "NIT Raipur",
    city: "Raipur",
    state: "Chhattisgarh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 750000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.nitrr.ac.in/",
    feeSourceUrl: "https://www.nitrr.ac.in/downloads/fees/Fees_2025/Fee%20Structure%202025-26.pdf",
    hostelPerYearInr: 35000,
    note: "Tuition ₹5L; total ₹6.97-7.81L incl. one-time fees. Full waiver below ₹1L income.",
  },
  {
    id: "iiit-allahabad",
    name: "IIIT Allahabad",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 850000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.iiita.ac.in/",
    feeSourceUrl: "https://www.iiita.ac.in/",
    hostelPerYearInr: 30000,
    note: "Top IIIT in India; ~₹8.4L total; CS placements rival mid-tier NITs at lower fees.",
  },
  {
    id: "iiit-lucknow",
    name: "IIIT Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1000000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://iiitl.ac.in/",
    feeSourceUrl: "https://iiitl.ac.in/",
    hostelPerYearInr: 42500,
    note: "Tuition ₹9.6L + hostel ~₹1.7L; CS/AI focus; PPP IIIT.",
  },
  {
    id: "iim-vizag",
    name: "IIM Visakhapatnam",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 2050000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iimv.ac.in/",
    feeSourceUrl: "https://www.iimv.ac.in/programs/pgp/pgp-prgm-fee",
    hostelPerYearInr: 90000,
    note: "Newer IIM; PGP 2025-27 tuition ~₹20.5L; rapidly improving placements.",
  },
  {
    id: "nliu-bhopal",
    name: "NLIU Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    cityTier: 2,
    type: "govt_state",
    courseFocus: "liberal_arts",
    approxTotalFeesInr: 2000000,
    durationYears: 5,
    mainEntranceExam: "CLAT",
    officialUrl: "https://www.nliu.ac.in/",
    feeSourceUrl: "https://www.nliu.ac.in/",
    hostelPerYearInr: 90000,
    note: "Top-5 NLU; 5-yr BA LLB total ~₹19.6-20.3L incl. hostel + mess.",
  },
  {
    id: "nift-bhubaneswar",
    name: "NIFT Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "design",
    approxTotalFeesInr: 1300000,
    durationYears: 4,
    mainEntranceExam: "NIFT",
    officialUrl: "https://www.nift.ac.in/bhubaneswar/",
    feeSourceUrl: "https://www.nift.ac.in/bhubaneswar/",
    hostelPerYearInr: 90000,
    note: "B.Des ~₹2.86L/yr (~₹13L total); fashion / textile / accessory design tracks.",
  },
  {
    id: "psg-coimbatore",
    name: "PSG College of Technology",
    city: "Coimbatore",
    state: "Tamil Nadu",
    cityTier: 2,
    type: "private_aided",
    courseFocus: "engineering",
    approxTotalFeesInr: 200000,
    durationYears: 4,
    mainEntranceExam: "TNEA / JEE Main",
    officialUrl: "https://www.psgtech.edu/",
    feeSourceUrl: "https://www.psgtech.edu/",
    hostelPerYearInr: 72000,
    note: "Govt-aided seats ~₹55K/yr tuition; legendary placements for an aided college.",
  },
  {
    id: "msu-baroda",
    name: "MS University of Baroda (Faculty of Tech & Engg)",
    city: "Vadodara",
    state: "Gujarat",
    cityTier: 2,
    type: "govt_state",
    courseFocus: "engineering",
    approxTotalFeesInr: 400000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.msubaroda.ac.in/",
    feeSourceUrl: "https://www.msubaroda.ac.in/",
    hostelPerYearInr: 25000,
    note: "State univ; B.E. tuition ~₹4.2L total. Very affordable in a heritage college town.",
  },

  // ─── TIER 3 — Premium institutes in small cities/towns ────────────────
  {
    id: "nit-rourkela",
    name: "NIT Rourkela",
    city: "Rourkela",
    state: "Odisha",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 600000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.nitrkl.ac.in/",
    feeSourceUrl: "https://www.nitrkl.ac.in/docs/Announcement/07082025113535080.pdf",
    hostelPerYearInr: 30000,
    note: "Top-tier NIT in a small steel town; strong CSE/Mech placements. Very low cost of living.",
  },
  {
    id: "nit-trichy",
    name: "NIT Trichy",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 650000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.nitt.edu/",
    feeSourceUrl: "https://www.nitt.edu/home/academics/fees_section/",
    hostelPerYearInr: 40000,
    note: "Consistently ranked #1 NIT; recruiter favourite for core engineering — one of the best ROIs nationwide.",
  },
  {
    id: "nit-warangal",
    name: "NIT Warangal",
    city: "Warangal",
    state: "Telangana",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 550000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.nitw.ac.in/",
    feeSourceUrl: "https://www.nitw.ac.in/main/AcademicSection/Tutionfee/",
    hostelPerYearInr: 60000,
    note: "Among top-3 NITs; strong CSE placements. One of the oldest RECs, cheap COL.",
  },
  {
    id: "nit-calicut",
    name: "NIT Calicut",
    city: "Kozhikode",
    state: "Kerala",
    cityTier: 2,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 700000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://nitc.ac.in/",
    feeSourceUrl: "https://nitc.ac.in/imgserver/uploads/attachments/nit-calicut-fee-structure-ug-pg-phd-for-the-ay-2025-26_0ffc1837-ac4a-4159-b530-21687a7a60c1_0.pdf",
    hostelPerYearInr: 80000,
    note: "Highly ranked NIT with strong Architecture and CSE; 2/3 tuition waiver below ₹5L family income.",
  },
  {
    id: "nit-hamirpur",
    name: "NIT Hamirpur",
    city: "Hamirpur",
    state: "Himachal Pradesh",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 700000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://nith.ac.in/",
    feeSourceUrl: "https://nith.ac.in/",
    hostelPerYearInr: 50000,
    note: "NIT in a tiny Himalayan town — dirt-cheap living, scenic campus, decent core branch placements.",
  },
  {
    id: "nit-silchar",
    name: "NIT Silchar",
    city: "Silchar",
    state: "Assam",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 550000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.nits.ac.in/",
    feeSourceUrl: "https://www.nits.ac.in/",
    hostelPerYearInr: 55000,
    note: "Northeast NIT with very low cost of living; income-based waivers make it near-free for sub-₹5L families.",
  },
  {
    id: "iit-bhu",
    name: "IIT (BHU) Varanasi",
    city: "Varanasi",
    state: "Uttar Pradesh",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1050000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://iitbhu.ac.in/",
    feeSourceUrl: "https://iitbhu.ac.in/contents/institute/main/docs/acad/fee_structure.pdf",
    hostelPerYearInr: 55000,
    note: "Full IIT brand with BHU heritage; ~₹10.4L total; cheap living in Varanasi.",
  },
  {
    id: "iit-roorkee",
    name: "IIT Roorkee",
    city: "Roorkee",
    state: "Uttarakhand",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 900000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitr.ac.in/",
    feeSourceUrl: "https://iitr.ac.in/Academics/static/Institute_Fee/2025-26/PG.pdf",
    hostelPerYearInr: 65000,
    note: "Top-5 IIT in a small Uttarakhand town; full tuition waivers below ₹1L income, 2/3 below ₹5L.",
  },
  {
    id: "iit-kgp",
    name: "IIT Kharagpur",
    city: "Kharagpur",
    state: "West Bengal",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1000000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitkgp.ac.in/",
    feeSourceUrl: "https://www.iitkgp.ac.in/fee-structure",
    hostelPerYearInr: 66000,
    note: "India's first IIT; largest campus; small railway town with very low COL.",
  },
  {
    id: "iit-mandi",
    name: "IIT Mandi",
    city: "Mandi",
    state: "Himachal Pradesh",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 850000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitmandi.ac.in/",
    feeSourceUrl: "https://www.iitmandi.ac.in/academics",
    hostelPerYearInr: 30000,
    note: "Newer IIT in the Himalayas; small batches; MCM scholarships for top-10 per branch below ₹6L income.",
  },
  {
    id: "iit-patna",
    name: "IIT Patna",
    city: "Patna",
    state: "Bihar",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1000000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitp.ac.in/",
    feeSourceUrl: "https://www.iitp.ac.in/index.php/students-corner/academic-fees",
    hostelPerYearInr: 60000,
    note: "Newer IIT with rising CSE placements; full waiver below ₹1L, 2/3 below ₹5L. Tuition only listed.",
  },
  {
    id: "iit-jodhpur",
    name: "IIT Jodhpur",
    city: "Jodhpur",
    state: "Rajasthan",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1000000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitj.ac.in/",
    feeSourceUrl: "https://www.iitj.ac.in/admission/index.php?id=fee_structure",
    hostelPerYearInr: 30000,
    note: "Newer IIT with strong AI/Data Science programs; cheap COL in Jodhpur, modern desert campus.",
  },
  {
    id: "iit-dharwad",
    name: "IIT Dharwad",
    city: "Dharwad",
    state: "Karnataka",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "engineering",
    approxTotalFeesInr: 1150000,
    durationYears: 4,
    mainEntranceExam: "JEE Advanced",
    officialUrl: "https://www.iitdh.ac.in/",
    feeSourceUrl: "https://www.iitdh.ac.in/student-fees",
    hostelPerYearInr: 54000,
    note: "Newest IIT in a Tier-3 Karnataka town; full SC/ST/PwD tuition waiver, low overall cost.",
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani (Pilani Campus)",
    city: "Pilani",
    state: "Rajasthan",
    cityTier: 3,
    type: "private",
    courseFocus: "engineering",
    approxTotalFeesInr: 2600000,
    durationYears: 4,
    mainEntranceExam: "BITSAT",
    officialUrl: "https://www.bits-pilani.ac.in/",
    feeSourceUrl: "https://www.bits-pilani.ac.in/admission/",
    hostelPerYearInr: 65000,
    note: "Premier private engineering school in a small Rajasthan town; placements rival top IITs.",
  },
  {
    id: "bit-mesra",
    name: "BIT Mesra",
    city: "Ranchi",
    state: "Jharkhand",
    cityTier: 3,
    type: "private_aided",
    courseFocus: "engineering",
    approxTotalFeesInr: 1700000,
    durationYears: 4,
    mainEntranceExam: "JEE Main",
    officialUrl: "https://www.bitmesra.ac.in/",
    feeSourceUrl: "https://bitmesra.ac.in/UploadedDocuments/admadmission/files/Financial%20information%20and%20fees%20payable%202025.pdf",
    hostelPerYearInr: 84000,
    note: "Legacy Birla institute with strong alumni network; Ranchi is cheap, BIT is respected for core engineering.",
  },
  {
    id: "iim-trichy",
    name: "IIM Tiruchirappalli",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 1950000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iimtrichy.ac.in/",
    feeSourceUrl: "https://www.iimtrichy.ac.in/en/fees",
    note: "Top-10 IIM; strong consulting + finance placements. One of the most affordable new IIMs in a low-COL town.",
  },
  {
    id: "iim-rohtak",
    name: "IIM Rohtak",
    city: "Rohtak",
    state: "Haryana",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 1800000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://www.iimrohtak.ac.in/",
    feeSourceUrl: "https://www.iimrohtak.ac.in/fee-structure.php?id=26",
    note: "One of the lowest IIM fees; growing brand near Delhi NCR with improving placements.",
  },
  {
    id: "iim-sambalpur",
    name: "IIM Sambalpur",
    city: "Sambalpur",
    state: "Odisha",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "management",
    approxTotalFeesInr: 1300000,
    durationYears: 2,
    mainEntranceExam: "CAT",
    officialUrl: "https://iimsambalpur.ac.in/",
    feeSourceUrl: "https://iimsambalpur.ac.in/wp-content/uploads/2025/05/MBA_Fee_Structure_IIMSBP.pdf",
    note: "Lowest-fee IIM in India. Great value pick if you clear CAT and want the IIM brand at the cheapest cost.",
  },
  {
    id: "aiims-jodhpur",
    name: "AIIMS Jodhpur",
    city: "Jodhpur",
    state: "Rajasthan",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "medical",
    approxTotalFeesInr: 50000,
    durationYears: 5,
    mainEntranceExam: "NEET-UG",
    officialUrl: "https://www.aiimsjodhpur.edu.in/",
    feeSourceUrl: "https://www.aiimsjodhpur.edu.in/students/feeStructure",
    hostelPerYearInr: 6000,
    note: "MBBS for under ~₹25K total — one of the cheapest premier medical degrees in the world. Tuition only.",
  },
  {
    id: "aiims-patna",
    name: "AIIMS Patna",
    city: "Patna",
    state: "Bihar",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "medical",
    approxTotalFeesInr: 50000,
    durationYears: 5,
    mainEntranceExam: "NEET-UG",
    officialUrl: "https://www.aiimspatna.edu.in/",
    feeSourceUrl: "https://www.aiimspatna.edu.in/",
    hostelPerYearInr: 6000,
    note: "MBBS total ~₹6K for entire 5.5 yrs (tuition only). AIIMS brand at negligible cost.",
  },
  {
    id: "aiims-bhubaneswar",
    name: "AIIMS Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    cityTier: 3,
    type: "govt_central",
    courseFocus: "medical",
    approxTotalFeesInr: 50000,
    durationYears: 5,
    mainEntranceExam: "NEET-UG",
    officialUrl: "https://aiimsbhubaneswar.nic.in/",
    feeSourceUrl: "https://aiimsbhubaneswar.nic.in/",
    hostelPerYearInr: 6000,
    note: "Highly-regarded AIIMS; near-zero tuition. One of the strongest medical brands in eastern India.",
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────

export const COURSE_FOCUS_LABELS: Record<CourseFocus, string> = {
  engineering: "Engineering",
  management: "Management",
  medical: "Medical",
  arts_sci: "Arts & Sci",
  design: "Design",
  liberal_arts: "Law / Liberal Arts",
  commerce: "Commerce",
};

export const COLLEGE_TYPE_LABELS: Record<CollegeType, string> = {
  govt_central: "Govt (central)",
  govt_state: "Govt (state)",
  private_aided: "Private (aided)",
  private: "Private",
};
